version: "3.9"

services:
  app:
    build: .
    image: thoughts-app:1.2.0
    working_dir: /app
    env_file: .env
    command:
      - php
      - -t
      - /app/public
      - -S
      - 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  database:
    image: mysql:8.2
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

volumes:
  db_data:
