<?php
use App\ViewHelpers\ViewHelper;
/**
 * @var ViewHelper $helper
 */
?>
<div dir="rtl">
    <div class="d-flex flex-space-around">
        <h1 class="t-size-4">فَاصِلَةٌ مَنْقُوطَةٌ</h1>
        <div id="logo">
            <pre dir="ltr">
     _.--._  _.--._
  ,-=.-":;:;:;\':;:;:;"-._
  \\\:;:;:;:;:;\:;:;:;:;:;\
   \\\:;:;:;:;:;\:;:;:;:;:;\
    \\\:;:;:;:;:;\:;:;:;:;:;\
     \\\:;:;:;:;:;\:;::;:;:;:\
      \\\;:;::;:;:;\:;:;:;::;:\
       \\\;;:;:_:--:\:_:--:_;:;\
        \\\_.-"      :      "-._\
         \`_..--""--.;.--""--.._=>
            </pre>
        </div>
    </div>
  <nav class="d-flex flex-space-around">
    <a href="/">الرئيسية</a>
    <?= $helper->getLocaleSwitch() ?>
    <span>الإعدادات</span>
  </nav>
  <hr>
</div>
