<div>
    <div class="d-flex flex-space-around">
        <div class="logo">
            <pre dir="ltr">
 ,.--.
//    \
\\    /
 `'--'
 ,.--.
//    \
\\     |
 `'-) /
   /.'
            </pre>
        </div>
        <h1 class="t-size-4">فَاصِلَةٌ مَنْقُوطَةٌ</h1>
        <div id="logo">
            <pre dir="ltr">
     _.--._  _.--._
  ,-=.-":;:;:;\':;:;:;"-._
  \\\:;:;:;:;:;\:;:;:;:;:;\
   \\\:;:;:;:;:;\:;:;:;:;:;\
    \\\:;:;:;:;:;\:;:;:;:;:;\
     \\\:;:;:;:;:;\:;::;:;:;:\
      \\\;:;::;:;:;\:;:;:;::;:\
       \\\;;:;:_:--:\:_:--:_;:;\
        \\\_.-"      :      "-._\
         \`_..--""--.;.--""--.._=>
            </pre>
        </div>
    </div>
  <nav class="d-flex flex-space-around">
<!--    <span>Menu1</span>-->
<!--    <span>Menu1</span>-->
<!--    <span>Menu1</span>-->
  </nav>
  <hr>
</div>
