<!DOCTYPE html>
<html lang="ar" dir="rtl">
<?php /** @var \App\ViewHelpers\ViewHelper $helper */ ?>
<?php $helper->includePartial('head') ?>
<body>
<div class="container">
  <div id="logo">
    <pre dir="ltr">
        _.--._  _.--._
      ,-=.-":;:;:;\':;:;:;"-._
      \\\:;:;:;:;:;\:;:;:;:;:;\
       \\\:;:;:;:;:;\:;:;:;:;:;\
        \\\:;:;:;:;:;\:;:;:;:;:;\
         \\\:;:;:;:;:;\:;::;:;:;:\
          \\\;:;::;:;:;\:;:;:;::;:\
           \\\;;:;:_:--:\:_:--:_;:;\
            \\\_.-"      :      "-._\
             \`_..--""--.;.--""--.._=>
    </pre>
  </div>
  <nav class="d-flex flex-space-around">
    <span>Menu1</span>
    <span>Menu1</span>
    <span>Menu1</span>
  </nav>
  <hr>
</div>
</body>
</html>
