<?php

use App\Entities\Notebook;
use App\Entities\Shelf;
use App\ViewHelpers\ShelvesHelper;

/**
 * @var ShelvesHelper $helper
 * @var Shelf $shelf
 * @var Notebook[] $notebooks
 */
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<?php $helper->includePartial('layout/head'); ?>
<body>
<div class="container">
    <?php $helper->includePartial('layout/header') ?>
    <h2 class="t-size-2"><?= $helper->getShelfTitle($shelf); ?></h2>
    <a href="/shelves/create?shelfId=<?= $shelf->getId() ?>">مجلد جديد +</a>
    <div class="d-flex">
        <?php $helper->includePartial('shared/booksArt') ?>
        <table>
            <thead>
                <tr>
                    <th>عنوان المجلد</th>
                    <th>تاريخ الإنشاء</th>
                    <th>الإجراءات</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($notebooks as $notebook): ?>
                    <tr>
                        <td><?= $helper->getNotebookTitle($notebook); ?></td>
                        <td><?= $helper->humanDate($notebook->getCreatedAt()) ?></td>
                        <td>
                            <a href="/notebooks?notebookId=<?= $notebook->getId() ?>">عرض</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
</body>
</html>
