<?php

use App\Entities\Shelf;
use App\ViewHelpers\HomeHelper;

/**
 * @var array $shelves
 * @var Shelf $shelf
 * @var HomeHelper $helper
 */
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<?php $helper->includePartial('layout/head'); ?>
<body>
    <div class="container">
        <?php $helper->includePartial('layout/header') ?>
        <div class="d-flex">
            <pre dir="ltr">
                       .--.                   .---.
                   .---|__|           .-.     |~~~|
                .--|===|--|_          |_|     |~~~|--.
                |  |===|  |'\     .---!~|  .--|   |--|
                |%%|   |  |.'\    |===| |--|%%|   |  |
                |%%|   |  |\.'\   |   | |__|  |   |  |
                |  |   |  | \  \  |===| |==|  |   |  |
                |  |   |__|  \.'\ |   |_|__|  |~~~|__|
                |  |===|--|   \.'\|===|~|--|%%|~~~|--|
                ^--^---'--^    `-'`---^-^--^--^---'--'
            </pre>
            <div>
                <ul>
                    <?php foreach ($shelves as $shelf): ?>
                        <li>
                            <h3><?= $helper->getTitle($shelf) ?></h3>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</body>
</html>
