<?php

use App\Entities\Shelf;
use App\ViewHelpers\HomeHelper;

/**
 * @var array $shelves
 * @var Shelf $shelf
 * @var HomeHelper $helper
 */
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<?php $helper->includePartial('layout/head'); ?>
<body>
    <div class="container">
        <?php $helper->includePartial('layout/header') ?>
        <div class="d-flex">
            <?php $helper->includePartial('shared/booksArt'); ?>
            <div>
                <ul>
                    <?php foreach ($shelves as $shelf): ?>
                        <li>
                            <a href="/shelves?shelfId=<?= $shelf->getId() ?>" class="t-size-2"><?= $helper->getTitle($shelf) ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</body>
</html>
