<?php

use App\Entities\Note;
use App\Entities\Notebook;
use App\ViewHelpers\ViewHelper;

/**
 * @var ViewHelper $helper
 * @var Notebook $notebook
 * @var Note[] $notes
 */
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<?php $helper->includePartial('layout/head'); ?>
<body>
<div class="container">
    <?php $helper->includePartial('layout/header') ?>
    <h2 class="t-size-2"><?= $notebook->getArabicTitle() ?></h2>
    <a href="/shelves?shelfId=<?= $notebook->getShelfId() ?>">عودة</a>
    |
    <a href="/notes/create?notebookId=<?= $notebook->getId() ?>">مفكرة جديدة +</a>
    <div class="d-flex">
        <?php $helper->includePartial('shared/booksArt') ?>
        <table>
            <thead>
            <tr>
                <th>عنوان المفكرة</th>
                <th>تاريخ الإنشاء</th>
                <th>تاريخ آخر تعديل</th>
                <th>الإجراءات</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($notes as $note): ?>
                    <?php $noteId = $note->getId() ?>
                    <tr>
                        <td><?= $note->getTitle() ?></td>
                        <td><?= $helper->humanDate($note->getCreatedAt()) ?></td>
                        <td><?= $helper->humanDate($note->getUpdatedAt()) ?></td>
                        <td>
                            <a href="/notes?noteId=<?= $noteId ?>">عرض</a>
                            |
                            <a href="/notes/edit?noteId=<?= $noteId ?>">تعديل</a>
                            |
                            <a href="/notes/delete?noteId=<?= $noteId ?>">حذف</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
</body>
</html>
