<?php

use App\Entities\Note;
use App\ViewHelpers\ViewHelper;

/**
 * @var ViewHelper $helper
 * @var Note $note
 */
?>
<!DOCTYPE html>
<html lang="<?= $helper->getLang() ?>" dir="<?= $helper->getDirection() ?>">
<?php $helper->includePartial('layout/head'); ?>
<body>
<div class="container">
    <?php $helper->includePartial('layout/header') ?>
    <h2 class="t-size-2"><?= $note->getTitle() ?></h2>
    <a href="/notebooks?notebookId=<?= $note->getNotebookId() ?>">عودة</a>
    |
    <span class="text-grey">بتاريخ <?= $helper->humanDate($note->getCreatedAt()) ?></span>
    <hr>
    <div><?= $note->getContent() ?></div>
</div>
</body>
</html>
